---
title: "LStricklin_Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(tigris)
library(tmap)
library(tmaptools)
library(leaflet)
complaints <- readRDS("~/github_stricklin/Data-Journalism-Consumer-Complaints/complaints.rds")

states <- tigris::states(cb=T)
complaints3 <- complaints %>%
  count(state)
complaints3_joined <- geo_join(states, complaints3, "STUSPS", "state")

mypalette <- colorNumeric("YlOrRd", domain = complaints3_joined$n)

popup_fcc <- paste0("Consumer Complaints Mar-Dec 2020: ", as.character(complaints3_joined$n))

map <- leaflet(complaints3_joined) %>% 
  addTiles() %>% 
    setView(-98.483330, 38.712046, zoom = 4) %>% 
      addPolygons(data = states, fillColor = ~mypalette(complaints3_joined$n), fillOpacity = 0.9, weight = 0.2, smoothFactor = 0.2, label = popup_fcc) %>% 
        addLegend(pal=mypalette, values=complaints3_joined$n, bins=5, position="bottomright", title="Consumer Complaints Mar-Dec 2020", labFormat=labelFormat(digits=0))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

map



```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

complaints2 <- complaints %>%
  count(date_received)

fig <- plot_ly(complaints2, x = ~date_received, y = ~n, type = 'scatter', mode = 'lines')
fig %>% layout(title = 'Number of Customer Complaints per Day', yaxis=list(title = 'Date Received'), xaxis = list(title='Number of Complaints'))
fig





```

### Chart C

```{r}

complaints4 <- complaints %>%
  count(company)
complaints4.0 <- complaints4 %>% filter(n > 4000)
complaints4.1 <- complaints4 %>% filter(n < 4000)
complaints4.2 <- sum(complaints4.1$n)
complaints4.3 <- c("Other",complaints4.2)
complaints5 <- rbind(complaints4.0, complaints4.3)

fig3 <- complaints5 %>% plot_ly(labels = ~company, values = ~n)
fig3 <- fig3 %>% add_pie(hole = 0.6)
fig3 <- fig3 %>% layout(title = "Companies Receiving Complaints in 2020", showlegend = F, xaxis = list(showgrid = FALSE, zerloine = FALSE, showticklabels = FALSE), yaxis = list(showgrid = FALSE, zerloine = FALSE, showticklabels = FALSE))
fig3

```

